# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to Firebase App Distributionp"
  lane :ios_beta_app do
    build_app(
      scheme: "Runner",
      archive_path: "./build/Runner.xcarchive",
      export_method: "development",
      output_directory: "./build/Runner",
    )
    firebase_app_distribution(
      app: "1:496948957842:ios:17ebb86034fdf7668e4c4b",
      groups_file: "./fastlane/firebase_app_distribution/groups.txt",
      release_notes_file: "./fastlane/firebase_app_distribution/release_notes.txt",
      ipa_path: "./build/Runner/Runner.ipa",
    )
  end
end